# Set this when the client runs from a subdirectory
relative_url_root: 

api_host: https://api.opensuse.org

# Add your username + password for the api here
api_username: test
api_password: test

#use_static: software.o.o

order_mails_to: promodvds@opensuse.org
