- version: 15.2
  order: 5
  releases:
  - date: '2020-01-13 12:00:00 UTC'
    state: 'Alpha'
  - date: '2020-02-20 18:00:00 UTC'
    state: 'Beta'
  - date: '2020-05-28 12:00:00 UTC'
    state: 'RC'
  - date: '2020-07-02 11:45:00 UTC'
    state: 'Stable'
- version: 15.1
  order: 4
  releases:
  - date: '2018-09-30 12:00:00 UTC'
    state: 'Alpha'
  - date: '2019-02-13 12:00:00 UTC'
    state: 'Beta'
  - date: '2019-04-16 12:00:00 UTC'
    state: 'RC'
  - date: '2019-05-22 12:00:00 UTC'
    state: 'Stable'
- version: 15.0
  order: 3
  releases:
  - date: '2018-01-31 00:00:00'
    state: 'Beta'
  - date: '2018-05-25 12:00:00 UTC'
    state: 'Stable'
  - date: '2019-12-03 00:00:00 UTC'
    state: 'EOL'
- version: 42.3
  order: 2
  releases:
  - date: '2017-07-08 00:00:00'
    state: 'RC'
  - date: '2017-07-26 00:00:00'
    state: 'Stable'
  - date: '2019-07-01 00:00:00 UTC'
    state: 'EOL'
- version: 42.2
  order: 1
  releases:
  - date: '2016-11-16 00:00:00'
    state: 'Stable'
  - date: '2018-01-26 00:00:00 UTC'
    state: 'EOL'
- version: 42.1
  order: 0
  releases:
  - date: '2016-11-16 00:00:00'
    state: 'Stable'
  - date: '2017-01-17 00:00:00 UTC'
    state: 'EOL'
